# -*- coding: utf-8 -*-
"""AI_part.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_W_WZJ-qeycrYYE_F1oBAVASaz1tPix
"""

import os
import shap
import tempfile
import pandas as pd
from groq import Groq
from gtts import gTTS
import concurrent.futures



_client = None

def _get_client():
    global _client
    if _client is None:
        api_key = os.environ.get("GROQ_API_KEY")
        if not api_key:
            raise ValueError("GROQ_API_KEY not set. Run os.environ first.")
        _client = Groq(api_key=api_key)
    return _client

FEATURE_LABELS = {
    "fantasy_avg_5":         "average fantasy points over last 5 matches",
    "fantasy_avg_3":         "average fantasy points over last 3 matches",
    "fantasy_avg_10":        "average fantasy points over last 10 matches",
    "wickets_avg_5":         "average wickets over last 5 matches",
    "wickets_avg_3":         "average wickets over last 3 matches",
    "runs_avg_5":            "average runs over last 5 matches",
    "runs_avg_3":            "average runs over last 3 matches",
    "sr_avg_5":              "strike rate over last 5 matches",
    "sr_avg_3":              "strike rate over last 3 matches",
    "economy_avg_5":         "economy rate over last 5 matches",
    "economy_avg_3":         "economy rate over last 3 matches",
    "venue_avg_fp":          "average fantasy points at this venue",
    "vs_team_avg_fp":        "historical performance vs this opposition",
    "career_avg_fp":         "career fantasy points average",
    "form_momentum":         "recent form momentum score",
    "fifty_rate_5":          "fifty-plus rate in last 5 matches",
    "fifty_rate_10":         "fifty-plus rate in last 10 matches",
    "fielding_avg_5":        "fielding contribution over last 5 matches",
    "fielding_avg_3":        "fielding contribution over last 3 matches",
    "career_matches":        "total career matches played",
    "days_since_last_match": "match fitness (days since last game)",
    "venue_format_avg_fp":   "average fantasy points at this venue in this format",
    "opp_batting_strength":  "opposition batting strength rating",
    "opp_bowling_strength":  "opposition bowling strength rating",
}

def compute_shap_for_squad(models, squad_df, feature_cols):
    squad_df = squad_df.copy().reset_index(drop=True)
    shap_results = {}

    for role, model in models.items():
        role_idx = squad_df.index[squad_df['role'] == role].tolist()
        if not role_idx:
            continue

        X         = squad_df.loc[role_idx, feature_cols].fillna(0).values
        shap_vals = shap.TreeExplainer(model).shap_values(X)

        for i, idx in enumerate(role_idx):
            contribs = sorted(zip(feature_cols, shap_vals[i]),
                              key=lambda x: abs(x[1]), reverse=True)
            shap_results[idx] = [
                {"feature": f, "impact": round(float(v), 3)}
                for f, v in contribs[:5]
            ]

    squad_df['shap_top5'] = squad_df.index.map(lambda i: shap_results.get(i, []))
    return squad_df


def humanize_shap(shap_top5):
    lines = []
    for item in shap_top5:
        label     = FEATURE_LABELS.get(item["feature"], item["feature"].replace("_", " "))
        direction = "boosted" if item["impact"] > 0 else "reduced"
        lines.append(f"{label} {direction} score by {abs(item['impact']):.2f} points")
    return ", ".join(lines)


import json

def _llm(prompt, force_json=False):
    """Core LLM call. Supports standard text or forced JSON output."""
    messages = [{"role": "user", "content": prompt}]
    
    if force_json:
        messages.insert(0, {"role": "system", "content": "You are an API that only returns valid JSON objects. No conversational text."})
        
    try:
        # Try to use Groq's native JSON mode
        response = _get_client().chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=messages,
            max_tokens=800,
            response_format={"type": "json_object"} if force_json else None
        )
    except:
        # Fallback if the specific groq library version doesn't support response_format
        response = _get_client().chat.completions.create(
            model="llama-3.1-8b-instant",
            messages=messages,
            max_tokens=800
        )
        
    return response.choices[0].message.content.strip()


def generate_all_commentaries(selected_df):
    selected_df = selected_df.copy()
    
    # 1. Build the Data Payload
    player_data_for_prompt = {}
    for _, row in selected_df.iterrows():
        player_key = row['player']
        cap_note = " (CAPTAIN)" if row.get('captain', False) else (" (VICE-CAPTAIN)" if row.get('vc', False) else "")
        player_data_for_prompt[player_key] = {
            "info": f"Role: {row['role']}, Team: {row['team']}{cap_note}, Expected: {round(row['predicted_fp'], 1)}",
            "key_factors": humanize_shap(row.get('shap_top5', []))
        }
        
    prompt = f"""You are a Dream11 fantasy cricket analyst.
Write exactly 2 sentences of specific, data-driven insight for each player below explaining their selection.

CRITICAL INSTRUCTIONS:
- You MUST return a single JSON object.
- The keys MUST be the exact player names provided.
- The values MUST be the 2-sentence commentary strings.

Player Data:
{json.dumps(player_data_for_prompt, indent=2)}
"""

    try:
        # 2. Call LLM with JSON forcing enabled
        response_text = _llm(prompt, force_json=True)
        
        # 3. Bulletproof JSON Extraction
        start_idx = response_text.find('{')
        end_idx = response_text.rfind('}')
        
        if start_idx != -1 and end_idx != -1:
            json_str = response_text[start_idx:end_idx+1]
            commentary_dict = json.loads(json_str)
        else:
            raise ValueError("No JSON brackets found in response.")
            
        # 4. Flatten the dictionary (in case the LLM nested it under {"insights": {...}})
        flat_dict = {}
        def flatten(d):
            for k, v in d.items():
                if isinstance(v, dict):
                    flatten(v)
                elif isinstance(v, str):
                    flat_dict[k] = v
        flatten(commentary_dict)
        
        # 5. Map back to dataframe with Fuzzy Matching Fallback
        def get_insight(name):
            # Try exact match first
            if name in flat_dict: 
                return flat_dict[name]
            # Try fuzzy match if the LLM slightly altered the name
            for k, v in flat_dict.items():
                if name.lower() in k.lower() or k.lower() in name.lower():
                    return v
            return "AI insight generation completed, but name mismatch occurred."
            
        selected_df['commentary'] = selected_df['player'].apply(get_insight)
        
    except Exception as e:
        print(f"LLM Parsing Error: {e}")
        selected_df['commentary'] = "AI insight temporarily unavailable."

    return selected_df

def _build_narration_script(selected_df, team1, team2):
    captain     = selected_df[selected_df['captain']].iloc[0]
    vc          = selected_df[selected_df['vc']].iloc[0]
    role_counts = selected_df['role'].value_counts().to_dict()
    total_pts   = selected_df['predicted_fp'].sum()

    player_lines = []
    for _, row in selected_df.iterrows():
        tag = " (Captain)" if row['captain'] else (" (Vice-Captain)" if row['vc'] else "")
        player_lines.append(
            f"{row['player']}{tag} — {row['role']} for {row['team']}, "
            f"expected to score around {row['predicted_fp']:.1f} points. "
            f"Key factors: {humanize_shap(row.get('shap_top5', []))}."
        )

    prompt = f"""You are a professional Dream11 fantasy cricket audio analyst.
Write a 30 to 40 second spoken commentary script for this predicted fantasy team.

Rules:
- Plain sentences only. No bullet points, no markdown, no headers.
- Never say "predicted points" — say "expected to score around X points".
- Mention the captain and vice-captain by name with one reason each.
- Mention 2-3 standout players with one specific reason each.
- End with one short motivating line for the user.

Match: {team1} vs {team2}
Composition: {role_counts} | Total expected score: {total_pts:.1f} pts
Captain: {captain['player']} ({captain['role']}, {captain['predicted_fp']:.1f} pts)
Vice-Captain: {vc['player']} ({vc['role']}, {vc['predicted_fp']:.1f} pts)

Player breakdown:
{chr(10).join(player_lines)}"""

    return _llm(prompt)

def generate_team_audio(selected_df, team1, team2, save_path=None, lang="en"):
    script = _build_narration_script(selected_df, team1, team2)
    tts    = gTTS(text=script, lang=lang, slow=False)

    if save_path is None:
        tmp       = tempfile.NamedTemporaryFile(suffix=".mp3", delete=False)
        save_path = tmp.name
        tmp.close()
    else:
        os.makedirs(os.path.dirname(save_path), exist_ok=True)

    tts.save(save_path)
    return save_path


def get_audio_script(selected_df, team1, team2):
    return _build_narration_script(selected_df, team1, team2)
